---
name: Security audit

'on':
  push:
  pull_request:
  schedule:
    - cron: "43 04 * * *"

jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: rustsec/audit-check@v1.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
